name: Build Workflow

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag from the tag stage"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          echo "Building project with tag ${{ inputs.tag }}"

      - name: Commit Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ inputs.tag }}" -m "Release ${{ inputs.tag }}"
          git push origin "${{ inputs.tag }}"
