name: Pipeline Main

on:
  workflow_dispatch: # allow manual triggering

permissions:
  contents: write # grant write access to github actions to commit

jobs:
  tag:
    name: Workflow Tag
    uses: ./.github/workflows/tag.yml

  build:
    name: Workflow Build
    needs: tag
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ needs.tag.outputs.tag }} # pass tag output to Build Stage

  release:
    name: Workflow Release
    needs: [tag, build] 
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.tag.outputs.tag }} # pass tag output to Release Stage
