name: Pipeline Main

on:
  workflow_dispatch: # allow manual triggering

jobs:
  tag:
    name: Workflow Tag
    uses: ./.github/workflows/tag.yml

  build:
    name: Workflow Build
    needs: tag # depends on the Workflow Tag
    uses: ./.github/workflows/build.yml

  release:
    name: Workflow Release
    needs: build # depends on the Workflow Build
    uses: ./.github/workflows/release.yml
