name: Pipeline Main

on:
  workflow_dispatch: # allow manual triggering

permissions:
  contents: write # Grant write access to contents for pushing tags

jobs:
  tag:
    name: Workflow Tag
    uses: ./.github/workflows/tag.yml

  build:
    name: Workflow Build
    needs: tag # depends on the Workflow Tag
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ needs.tag.outputs.tag }} # Pass tag output to Build Stage

  release:
    name: Workflow Release
    needs: build # depends on the Workflow Build
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.tag.outputs.tag }} # Pass tag output to Release Stage
