name: Release Workflow

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag from the tag stage"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Tag
        run: |
          echo "Releasing project with tag ${{ inputs.tag }}"
