name: Workflow Release

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag from the workflow tag"
        required: true
        type: string
  push: # prevents triggering it independently, use pipeline.yml
    branches-ignore:
      - '**'

jobs:
  release:
    # example context variables
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Tag
        run: |
          echo "Releasing project with tag ${{ inputs.tag }}"

      # example default environment variables
      - name: example default environment variables
        run: |
          echo "GITHUB_REF = $GITHUB_REF" 

      # example custom environment variables
      - name: example custom environment variables
        run: |
          echo "Hello $First_Name"
        env:
          First_Name: Matt
