name: Workflow Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "The generated tag version"
        value: ${{ jobs.tag.outputs.tag }}
  push: # prevents triggering it independently, use pipeline.yml
    branches-ignore:
      - '**'
  
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Tag
        id: generate-tag
        run: |
          version="v0.0.${{ github.run_number }}"
          echo "tag=$version" >> $GITHUB_ENV
          echo $version
        env:
          version: v0.0.${{ github.run_number }}