name: Workflow Main

on:
  # allow manual triggering
  workflow_dispatch:

  # triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write # grant write access to github actions to commit

jobs:
  tag:
    name: Workflow Tag
    uses: ./.github/workflows/tag.yml

  build:
    name: Workflow Build
    needs: tag
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ needs.tag.outputs.tag }} # pass tag output to Build Stage

  release:
    name: Workflow Release
    needs: [tag, build] 
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.tag.outputs.tag }} # pass tag output to Release Stage
